
USE camunda;
SET SESSION FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS WORKER_NODE;
CREATE TABLE WORKER_NODE
(
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'auto increment id',
    HOST_NAME VARCHAR(64) NOT NULL COMMENT 'host name',
    PORT VARCHAR(64) NOT NULL COMMENT 'port',
    TYPE INT NOT NULL COMMENT 'node type: CONTAINER(1), ACTUAL(2), FAKE(3)',
    LAUNCH_DATE DATE NOT NULL COMMENT 'launch date',
    MODIFIED TIMESTAMP NOT NULL COMMENT 'modified time',
    CREATED TIMESTAMP NOT NULL COMMENT 'created time',
    PRIMARY KEY(ID)
)
    COMMENT='DB WorkerID Assigner for UID Generator',ENGINE = INNODB;

DROP TABLE IF EXISTS DEFINE_KEY;
DROP TABLE IF EXISTS BUSINESS_DESCRIPTION;
DROP TABLE IF EXISTS OPERATION;
DROP TABLE IF EXISTS BUSINESS;

DROP TABLE IF EXISTS BUSINESS_DEFINE;
DROP TABLE IF EXISTS BUSINESS_FILE_DEFINE;

DROP TABLE IF EXISTS BUSINESS_FILE;
DROP TABLE IF EXISTS BUSINESS_DOCUMENT;

CREATE TABLE BUSINESS
(
    ID bigint NOT NULL,
    STATUS varchar(9) NOT NULL,
    CREATE_TIME datetime NOT NULL,
    COMPLETE_TIME datetime,
    DEFINE varchar(32) NOT NULL,
    NAME varchar(32) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;




CREATE TABLE BUSINESS_DESCRIPTION
(
    ID bigint NOT NULL,
    DESCRIPTION text NOT NULL,
    _KEYS varchar(1024),
    TAGS text,
    SOURCE VARCHAR(8) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE OPERATION
(
    BUSINESS_ID bigint NOT NULL,
    OPERATION_TIME datetime NOT NULL,
    TYPE varchar(16) NOT NULL,
    EMP_ID varchar(32),
    EMP_NAME varchar(32) NOT NULL,
    TASK_NAME varchar(32) NULL,
    DESCRIPTION varchar(512),
    ID bigint NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

CREATE TABLE DEFINE_KEY
(
    BUSINESS bigint NOT NULL,
    CATEGORY varchar(16) NOT NULL,
    _KEYS varchar(1024) NOT NULL,
    PRIMARY KEY (BUSINESS, CATEGORY)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;





CREATE TABLE BUSINESS_DEFINE
(
    NAME varchar(32) NOT NULL,
    ID varchar(32) NOT NULL,
    PROCESS varchar(32),
    DESCRIPTION_TEMPLATE text NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

CREATE TABLE BUSINESS_FILE_DEFINE
(
    BUSINESS varchar(32) NOT NULL,
    _ORDER int NOT NULL,
    NAME varchar(512) NOT NULL,
    TYPE varchar(4) NOT NULL,
    EL varchar(512) NULL,
    DESCRIPTION varchar(1024),
    PRIMARY KEY (BUSINESS, _ORDER)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;





CREATE TABLE BUSINESS_DOCUMENT
(
    NAME varchar(512) NOT NULL,
    BUSINESS_ID bigint NOT NULL,
    ID bigint NOT NULL,
    PAGE_COUNT int NOT NULL,
    NEED boolean NOT NULL,
    _ORDER int NOT NULL,
    DESCRIPTION varchar(1024) NULL,
    PRIMARY KEY (ID),
    CONSTRAINT BUSINESS_DOC_NAME_UNIQUE UNIQUE (NAME, BUSINESS_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE BUSINESS_FILE
(
    FILE_ID bigint NOT NULL,
    _ORDER int NOT NULL,
    FILE_ITEM_ID varchar(32) NOT NULL,
    MD5 varchar(32),
    UPLOAD_TIME datetime NOT NULL,
    FILE_TYPE varchar(512) NOT NULL,
    FILE_SIZE int,
    EXT_NAME varchar(8) NULL,
    PRIMARY KEY (FILE_ITEM_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;
/* Create Foreign Keys */
ALTER TABLE BUSINESS_FILE
    ADD FOREIGN KEY (FILE_ID)
        REFERENCES BUSINESS_DOCUMENT (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE BUSINESS_FILE_DEFINE
    ADD FOREIGN KEY (BUSINESS)
        REFERENCES BUSINESS_DEFINE (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;



ALTER TABLE BUSINESS_DESCRIPTION
    ADD FOREIGN KEY (ID)
        REFERENCES BUSINESS (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE OPERATION
    ADD FOREIGN KEY (BUSINESS_ID)
        REFERENCES BUSINESS (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE DEFINE_KEY
    ADD FOREIGN KEY (BUSINESS)
        REFERENCES BUSINESS_DESCRIPTION (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;

SET SESSION FOREIGN_KEY_CHECKS=1;