USE CONSTRUCT;

SET SESSION FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS DFCI;
DROP TABLE IF EXISTS DFCC;
DROP TABLE IF EXISTS DFCT;
DROP TABLE IF EXISTS DFCL;

DROP TABLE IF EXISTS FIRE_PROJECT_BUILD;
DROP TABLE IF EXISTS FIRE_CHECK_BUILD;
DROP TABLE IF EXISTS FIRE_CHECK_FIT;
DROP TABLE IF EXISTS FIRE_CHECK_USE_CHANGE;
DROP TABLE IF EXISTS FIRE_CHECK_REPORT;
DROP TABLE IF EXISTS FIRE_CHECK_STORE_SQUARE;
DROP TABLE IF EXISTS FIRE_CHECK_STORE_TIN;
DROP TABLE IF EXISTS FIRE_CHECK_CONTENT;
DROP TABLE IF EXISTS FIRE_CHECK_SUB_ITEM;
DROP TABLE IF EXISTS FIRE_CHECK_ITEM;
DROP TABLE IF EXISTS FIRE_CHECK_TABLE;
DROP TABLE IF EXISTS FIRE_CHECK_WARM;
DROP TABLE IF EXISTS FIRE_JOIN_CORP;
DROP TABLE IF EXISTS FIRE_PROJECT;
DROP TABLE IF EXISTS FIRE_CHECK;
DROP TABLE IF EXISTS FIRE_CHECK_INFO;
DROP TABLE IF EXISTS FIRE_FILE_CHECK;


CREATE TABLE DFCC
(
    NAME varchar(32) NOT NULL,
    _ORDER int NOT NULL,
    ID bigint NOT NULL,
    TABLE_ID bigint NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE DFCI
(
    _ORDER int NOT NULL,
    NAME varchar(32) NOT NULL,
    ID bigint NOT NULL,
    ITEM_ID bigint NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE DFCL
(
    _ORDER int NOT NULL,
    NAME varchar(1024) NOT NULL,
    _REQUIRE varchar(1024),
    PARENT bigint NOT NULL,
    LEVEL int NOT NULL,
    ID bigint NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE DFCT
(
    _ORDER int NOT NULL,
    NAME varchar(32) NOT NULL,
    ID bigint NOT NULL,
    PART boolean NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


ALTER TABLE DFCI
    ADD FOREIGN KEY (ITEM_ID)
        REFERENCES DFCC (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE DFCL
    ADD FOREIGN KEY (PARENT)
        REFERENCES DFCI (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE DFCC
    ADD FOREIGN KEY (TABLE_ID)
        REFERENCES DFCT (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;



CREATE TABLE FIRE_CHECK
(
    ID bigint NOT NULL,
    STATUS varchar(11) NOT NULL,
    NO_ACCEPT_TYPE varchar(11) NULL,
    APPLY_TIME datetime NOT NULL,
    REG_TIME datetime,
    APPLY_TYPE varchar(16) NOT NULL,
    CORP_CODE bigint NOT NULL,
    OPINION text,
    MEMO varchar(1024),
    INFO bigint NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIRE_CHECK_BUILD
(
    ID bigint NOT NULL,
    FIRE_RATING int NOT NULL,
    DANGER int NOT NULL,
    BUILD_CODE bigint NOT NULL,
    FIRE_CHECK bigint NOT NULL,
    USE_PROPERTY varchar(16) NULL,
    OPINION text,
    PASS boolean,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIRE_CHECK_CONTENT
(
    ID bigint NOT NULL,
    NAME varchar(1024) NOT NULL,
    PARTS varchar(32),
    _REQUIRE varchar(1024),
    LEVEL int NOT NULL,
    QUALIFIED boolean NOT NULL,
    DESCRIPTION varchar(32),
    ITEM_ID bigint NOT NULL,
    _ORDER int NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIRE_CHECK_FIT
(
    ID bigint NOT NULL,
    PART varchar(64) NOT NULL,
    AREA decimal(19,2),
    LAYERS varchar(16),
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

CREATE TABLE FIRE_CHECK_USE_CHANGE
(
    ID bigint NOT NULL,
    USE_PROPERTY varchar(16) NULL,
    OLD_USE varchar(16),
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIRE_CHECK_INFO
(
    PROJECT_CODE bigint NOT NULL,
    CONTACTS varchar(64),
    TEL varchar(16),
    ID bigint NOT NULL,
    IN_RANDOM boolean NOT NULL,
    CONSTRUCTION_FILE varchar(32),
    CON_FILE_DATE datetime,
    DESIGN_FILE varchar(32),
    DESIGN_FILE_DATE datetime,
    PART boolean NOT NULL,
    CONCLUSION varchar(1024),
    QUALIFIED boolean NOT NULL,
    SPECIAL boolean NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIRE_CHECK_ITEM
(
    ID bigint NOT NULL,
    NAME varchar(32) NOT NULL,
    _ORDER int NOT NULL,
    QUALIFIED boolean NOT NULL,
    TABLE_ID bigint NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIRE_CHECK_REPORT
(
    NAME varchar(32) NOT NULL,
    FILE_ID varchar(32) NOT NULL,
    MD5 varchar(32),
    UPLOAD_TIME datetime NOT NULL,
    FILE_SIZE int,
    FILE_TYPE varchar(512) NOT NULL,
    FAIL boolean NOT NULL,
    BUSINESS bigint NOT NULL,
    PRIMARY KEY (FILE_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIRE_CHECK_STORE_SQUARE
(
    ID bigint NOT NULL,
    AREA decimal(19,2),
    NAME varchar(32),
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIRE_CHECK_STORE_TIN
(
    ID bigint NOT NULL,
    LOCATION varchar(64),
    AREA decimal(19,2),
    TYPE varchar(10) NOT NULL,
    STORE_TYPE varchar(6) NOT NULL,
    NAME varchar(32),
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIRE_CHECK_SUB_ITEM
(
    ITEM_ID bigint NOT NULL,
    _ORDER int NOT NULL,
    NAME varchar(32) NOT NULL,
    COUNT int,
    FULL boolean NOT NULL,
    ID bigint NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIRE_CHECK_TABLE
(
    NAME varchar(32) NOT NULL,
    _ORDER int NOT NULL,
    CHECK_ID bigint NOT NULL,
    ID bigint NOT NULL,
    PART boolean NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIRE_CHECK_WARM
(
    ID bigint NOT NULL,
    TYPE varchar(2) NOT NULL,
    LAYERS varchar(16),
    PART varchar(32),
    MATERIAL varchar(32),
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIRE_JOIN_CORP
(
    CORP_CODE bigint NOT NULL,
    CORP_TYPE varchar(16) NOT NULL,
    PROJECT bigint NOT NULL,
    LEVEL int NOT NULL,
    NAME varchar(128) NOT NULL,
    REG_ID_TYPE varchar(16) NOT NULL,
    REG_ID_NUMBER varchar(32) NOT NULL,
    CONTACTS varchar(64),
    CONTACTS_ID varchar(32) NULL,
    TEL varchar(16),
    OWNER_ID_NUMBER varchar(32),
    OWNER_ID_TYPE varchar(16) NOT NULL,
    OWNER_NAME varchar(32) NOT NULL,
    PRIMARY KEY (CORP_CODE, CORP_TYPE, PROJECT)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIRE_PROJECT
(
    ID bigint NOT NULL,
    NAME varchar(256) NOT NULL,
    ADDRESS varchar(512),
    PROPERTY varchar(6),
    TYPE varchar(19) NOT NULL,
    ALL_AREA decimal(19,2),
    AREA decimal(19,2),
    PUT_MONEY decimal(19,2),
    MAIN_PROJECT_LEVEL varchar(8) NOT NULL,
    CORPS text,
    TAGS varchar(1024),
    MODIFY_FIT boolean,
    MODIFY_WARM boolean,
    MODIFY_USE boolean,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIRE_PROJECT_BUILD
(
    ID bigint NOT NULL,
    NAME varchar(32) NOT NULL,
    STRUCTURE varchar(16) NOT NULL,
    GROUND_FLOOR_COUNT int,
    UNDER_FLOOR_COUNT int,
    HEIGHT decimal(19,2),
    _LENGTH decimal(19,2),
    ALL_AREA decimal(19,2),
    GROUND_AREA decimal(19,2),
    UNDER_AREA decimal(19,2),
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE FIRE_FILE_CHECK
(
    ID bigint NOT NULL,
    PASS boolean NOT NULL,
    NAME varchar(64) NOT NULL,
    BUSINESS bigint NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

/* Create Foreign Keys */


ALTER TABLE FIRE_CHECK_REPORT
    ADD FOREIGN KEY (BUSINESS)
        REFERENCES FIRE_CHECK (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE FIRE_PROJECT_BUILD
    ADD FOREIGN KEY (ID)
        REFERENCES FIRE_CHECK_BUILD (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE FIRE_CHECK
    ADD FOREIGN KEY (INFO)
        REFERENCES FIRE_CHECK_INFO (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE FIRE_CHECK_BUILD
    ADD FOREIGN KEY (FIRE_CHECK)
        REFERENCES FIRE_CHECK_INFO (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE FIRE_CHECK_FIT
    ADD FOREIGN KEY (ID)
        REFERENCES FIRE_CHECK_INFO (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;

ALTER TABLE FIRE_CHECK_USE_CHANGE
    ADD FOREIGN KEY (ID)
        REFERENCES FIRE_CHECK_INFO (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE FIRE_CHECK_STORE_SQUARE
    ADD FOREIGN KEY (ID)
        REFERENCES FIRE_CHECK_INFO (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE FIRE_CHECK_STORE_TIN
    ADD FOREIGN KEY (ID)
        REFERENCES FIRE_CHECK_INFO (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE FIRE_CHECK_TABLE
    ADD FOREIGN KEY (CHECK_ID)
        REFERENCES FIRE_CHECK_INFO (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE FIRE_CHECK_WARM
    ADD FOREIGN KEY (ID)
        REFERENCES FIRE_CHECK_INFO (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE FIRE_PROJECT
    ADD FOREIGN KEY (ID)
        REFERENCES FIRE_CHECK_INFO (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE FIRE_CHECK_SUB_ITEM
    ADD FOREIGN KEY (ITEM_ID)
        REFERENCES FIRE_CHECK_ITEM (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE FIRE_CHECK_CONTENT
    ADD FOREIGN KEY (ITEM_ID)
        REFERENCES FIRE_CHECK_SUB_ITEM (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE FIRE_CHECK_ITEM
    ADD FOREIGN KEY (TABLE_ID)
        REFERENCES FIRE_CHECK_TABLE (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE FIRE_JOIN_CORP
    ADD FOREIGN KEY (PROJECT)
        REFERENCES FIRE_PROJECT (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;

ALTER TABLE FIRE_FILE_CHECK
    ADD FOREIGN KEY (BUSINESS)
        REFERENCES FIRE_CHECK (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;

SET SESSION FOREIGN_KEY_CHECKS=1;
